// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "Runlet/internal/domain/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AttemptRepository is an autogenerated mock type for the AttemptRepository type
type AttemptRepository struct {
	mock.Mock
}

// AddAttempt provides a mock function with given fields: ctx, studentid, problemId, done, lastTests
func (_m *AttemptRepository) AddAttempt(ctx context.Context, studentid int, problemId int, done bool, lastTests entities.TestCases) error {
	ret := _m.Called(ctx, studentid, problemId, done, lastTests)

	if len(ret) == 0 {
		panic("no return value specified for AddAttempt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, bool, entities.TestCases) error); ok {
		r0 = rf(ctx, studentid, problemId, done, lastTests)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckProblemIsDone provides a mock function with given fields: ctx, problemId, studentId
func (_m *AttemptRepository) CheckProblemIsDone(ctx context.Context, problemId int, studentId int) bool {
	ret := _m.Called(ctx, problemId, studentId)

	if len(ret) == 0 {
		panic("no return value specified for CheckProblemIsDone")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, int, int) bool); ok {
		r0 = rf(ctx, problemId, studentId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetCurrentResults provides a mock function with given fields: ctx, problemId, studentId
func (_m *AttemptRepository) GetCurrentResults(ctx context.Context, problemId int, studentId int) (entities.TestCases, error) {
	ret := _m.Called(ctx, problemId, studentId)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentResults")
	}

	var r0 entities.TestCases
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (entities.TestCases, error)); ok {
		return rf(ctx, problemId, studentId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) entities.TestCases); ok {
		r0 = rf(ctx, problemId, studentId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.TestCases)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, problemId, studentId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAttemptRepository creates a new instance of AttemptRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAttemptRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AttemptRepository {
	mock := &AttemptRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
