version: "2"
run:
  timeout: "1m"
  issues-exit-code: 1
  allow-parallel-runners: false
  allow-serial-runners: true
  go: "1.24.5"
  relative-path-mode: wd
  
linters:
  exclusions:
    paths:
      - "tests/.*"