FROM golang:1.24.5-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

RUN go install entgo.io/ent/cmd/ent@v0.14.5

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o app ./cmd/server
RUN CGO_ENABLED=0 GOOS=linux go build -o migrate ./cmd/migrations

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/app .
COPY --from=builder /app/migrate .


EXPOSE 8080
