// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "Runlet/internal/domain/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ClassRepository is an autogenerated mock type for the ClassRepository type
type ClassRepository struct {
	mock.Mock
}

// CreateClass provides a mock function with given fields: ctx, num
func (_m *ClassRepository) CreateClass(ctx context.Context, num string) (entities.Class, error) {
	ret := _m.Called(ctx, num)

	if len(ret) == 0 {
		panic("no return value specified for CreateClass")
	}

	var r0 entities.Class
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Class, error)); ok {
		return rf(ctx, num)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Class); ok {
		r0 = rf(ctx, num)
	} else {
		r0 = ret.Get(0).(entities.Class)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, num)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteClass provides a mock function with given fields: ctx, id
func (_m *ClassRepository) DeleteClass(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClass")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllClasses provides a mock function with given fields: ctx
func (_m *ClassRepository) GetAllClasses(ctx context.Context) ([]entities.Class, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllClasses")
	}

	var r0 []entities.Class
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.Class, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.Class); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Class)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClass provides a mock function with given fields: ctx, num
func (_m *ClassRepository) GetClass(ctx context.Context, num string) (entities.Class, error) {
	ret := _m.Called(ctx, num)

	if len(ret) == 0 {
		panic("no return value specified for GetClass")
	}

	var r0 entities.Class
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Class, error)); ok {
		return rf(ctx, num)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Class); ok {
		r0 = rf(ctx, num)
	} else {
		r0 = ret.Get(0).(entities.Class)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, num)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClassRepository creates a new instance of ClassRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClassRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClassRepository {
	mock := &ClassRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
