// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "Runlet/internal/domain/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CourseRepository is an autogenerated mock type for the CourseRepository type
type CourseRepository struct {
	mock.Mock
}

// AddClasses provides a mock function with given fields: ctx, courseId, classesIds
func (_m *CourseRepository) AddClasses(ctx context.Context, courseId int, classesIds []int) ([]entities.Class, error) {
	ret := _m.Called(ctx, courseId, classesIds)

	if len(ret) == 0 {
		panic("no return value specified for AddClasses")
	}

	var r0 []entities.Class
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []int) ([]entities.Class, error)); ok {
		return rf(ctx, courseId, classesIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, []int) []entities.Class); ok {
		r0 = rf(ctx, courseId, classesIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Class)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, []int) error); ok {
		r1 = rf(ctx, courseId, classesIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckStudent provides a mock function with given fields: ctx, studentId, courseId
func (_m *CourseRepository) CheckStudent(ctx context.Context, studentId int, courseId int) bool {
	ret := _m.Called(ctx, studentId, courseId)

	if len(ret) == 0 {
		panic("no return value specified for CheckStudent")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, int, int) bool); ok {
		r0 = rf(ctx, studentId, courseId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// CreateCourse provides a mock function with given fields: ctx, title, description, classesIds, teachersIds
func (_m *CourseRepository) CreateCourse(ctx context.Context, title string, description string, classesIds []int, teachersIds []int) (entities.Course, error) {
	ret := _m.Called(ctx, title, description, classesIds, teachersIds)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourse")
	}

	var r0 entities.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []int, []int) (entities.Course, error)); ok {
		return rf(ctx, title, description, classesIds, teachersIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []int, []int) entities.Course); ok {
		r0 = rf(ctx, title, description, classesIds, teachersIds)
	} else {
		r0 = ret.Get(0).(entities.Course)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []int, []int) error); ok {
		r1 = rf(ctx, title, description, classesIds, teachersIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteClasses provides a mock function with given fields: ctx, courseId, classesIds
func (_m *CourseRepository) DeleteClasses(ctx context.Context, courseId int, classesIds []int) ([]entities.Class, error) {
	ret := _m.Called(ctx, courseId, classesIds)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClasses")
	}

	var r0 []entities.Class
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []int) ([]entities.Class, error)); ok {
		return rf(ctx, courseId, classesIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, []int) []entities.Class); ok {
		r0 = rf(ctx, courseId, classesIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Class)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, []int) error); ok {
		r1 = rf(ctx, courseId, classesIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCourse provides a mock function with given fields: ctx, id
func (_m *CourseRepository) DeleteCourse(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllCourses provides a mock function with given fields: ctx
func (_m *CourseRepository) GetAllCourses(ctx context.Context) ([]entities.Course, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCourses")
	}

	var r0 []entities.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.Course, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.Course); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllStudentCourses provides a mock function with given fields: ctx, studentId
func (_m *CourseRepository) GetAllStudentCourses(ctx context.Context, studentId int) ([]entities.Course, error) {
	ret := _m.Called(ctx, studentId)

	if len(ret) == 0 {
		panic("no return value specified for GetAllStudentCourses")
	}

	var r0 []entities.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]entities.Course, error)); ok {
		return rf(ctx, studentId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []entities.Course); ok {
		r0 = rf(ctx, studentId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, studentId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCourseById provides a mock function with given fields: ctx, id
func (_m *CourseRepository) GetCourseById(ctx context.Context, id int) (entities.Course, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCourseById")
	}

	var r0 entities.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (entities.Course, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) entities.Course); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.Course)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCourseRepository creates a new instance of CourseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseRepository {
	mock := &CourseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
