// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "Runlet/internal/domain/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ProblemRepository is an autogenerated mock type for the ProblemRepository type
type ProblemRepository struct {
	mock.Mock
}

// CreateProblem provides a mock function with given fields: ctx, title, description, courseId
func (_m *ProblemRepository) CreateProblem(ctx context.Context, title string, description string, courseId int) (entities.Problem, error) {
	ret := _m.Called(ctx, title, description, courseId)

	if len(ret) == 0 {
		panic("no return value specified for CreateProblem")
	}

	var r0 entities.Problem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) (entities.Problem, error)); ok {
		return rf(ctx, title, description, courseId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) entities.Problem); ok {
		r0 = rf(ctx, title, description, courseId)
	} else {
		r0 = ret.Get(0).(entities.Problem)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, title, description, courseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProblem provides a mock function with given fields: ctx, problemId
func (_m *ProblemRepository) DeleteProblem(ctx context.Context, problemId int) error {
	ret := _m.Called(ctx, problemId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProblem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, problemId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCourseProblems provides a mock function with given fields: ctx, courseId
func (_m *ProblemRepository) GetCourseProblems(ctx context.Context, courseId int) ([]entities.Problem, error) {
	ret := _m.Called(ctx, courseId)

	if len(ret) == 0 {
		panic("no return value specified for GetCourseProblems")
	}

	var r0 []entities.Problem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]entities.Problem, error)); ok {
		return rf(ctx, courseId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []entities.Problem); ok {
		r0 = rf(ctx, courseId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Problem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, courseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProblem provides a mock function with given fields: ctx, id
func (_m *ProblemRepository) GetProblem(ctx context.Context, id int) (entities.Problem, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProblem")
	}

	var r0 entities.Problem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (entities.Problem, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) entities.Problem); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.Problem)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProblemTestCases provides a mock function with given fields: ctx, problemId
func (_m *ProblemRepository) GetProblemTestCases(ctx context.Context, problemId int) (entities.TestCases, error) {
	ret := _m.Called(ctx, problemId)

	if len(ret) == 0 {
		panic("no return value specified for GetProblemTestCases")
	}

	var r0 entities.TestCases
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (entities.TestCases, error)); ok {
		return rf(ctx, problemId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) entities.TestCases); ok {
		r0 = rf(ctx, problemId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.TestCases)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, problemId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProblem provides a mock function with given fields: ctx, problemId, title, description
func (_m *ProblemRepository) UpdateProblem(ctx context.Context, problemId int, title string, description string) error {
	ret := _m.Called(ctx, problemId, title, description)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProblem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) error); ok {
		r0 = rf(ctx, problemId, title, description)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProblemRepository creates a new instance of ProblemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProblemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProblemRepository {
	mock := &ProblemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
