// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "Runlet/internal/application/dto"
	entities "Runlet/internal/domain/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Runner is an autogenerated mock type for the Runner type
type Runner struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, studentId, problemid, solution, cases
func (_m *Runner) Run(ctx context.Context, studentId int, problemid int, solution dto.CodeSolution, cases []dto.RunData) (entities.TestCases, error) {
	ret := _m.Called(ctx, studentId, problemid, solution, cases)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 entities.TestCases
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, dto.CodeSolution, []dto.RunData) (entities.TestCases, error)); ok {
		return rf(ctx, studentId, problemid, solution, cases)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, dto.CodeSolution, []dto.RunData) entities.TestCases); ok {
		r0 = rf(ctx, studentId, problemid, solution, cases)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.TestCases)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, dto.CodeSolution, []dto.RunData) error); ok {
		r1 = rf(ctx, studentId, problemid, solution, cases)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRunner creates a new instance of Runner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Runner {
	mock := &Runner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
