// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "Runlet/internal/domain/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// StudentRepository is an autogenerated mock type for the StudentRepository type
type StudentRepository struct {
	mock.Mock
}

// CreateStudent provides a mock function with given fields: ctx, name, email, hashedPassword, classID
func (_m *StudentRepository) CreateStudent(ctx context.Context, name string, email string, hashedPassword string, classID int) (entities.Student, error) {
	ret := _m.Called(ctx, name, email, hashedPassword, classID)

	if len(ret) == 0 {
		panic("no return value specified for CreateStudent")
	}

	var r0 entities.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int) (entities.Student, error)); ok {
		return rf(ctx, name, email, hashedPassword, classID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int) entities.Student); ok {
		r0 = rf(ctx, name, email, hashedPassword, classID)
	} else {
		r0 = ret.Get(0).(entities.Student)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int) error); ok {
		r1 = rf(ctx, name, email, hashedPassword, classID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteStudent provides a mock function with given fields: ctx, id
func (_m *StudentRepository) DeleteStudent(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStudent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetStudent provides a mock function with given fields: ctx, id
func (_m *StudentRepository) GetStudent(ctx context.Context, id int) (entities.Student, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetStudent")
	}

	var r0 entities.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (entities.Student, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) entities.Student); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.Student)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudentByEmail provides a mock function with given fields: ctx, email
func (_m *StudentRepository) GetStudentByEmail(ctx context.Context, email string) (entities.Student, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentByEmail")
	}

	var r0 entities.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Student, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Student); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(entities.Student)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStudentRepository creates a new instance of StudentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStudentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StudentRepository {
	mock := &StudentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
