// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "Runlet/internal/domain/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TeacherRepository is an autogenerated mock type for the TeacherRepository type
type TeacherRepository struct {
	mock.Mock
}

// CreateTeacher provides a mock function with given fields: ctx, name, email, hashedPassword
func (_m *TeacherRepository) CreateTeacher(ctx context.Context, name string, email string, hashedPassword string) (entities.Teacher, error) {
	ret := _m.Called(ctx, name, email, hashedPassword)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeacher")
	}

	var r0 entities.Teacher
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (entities.Teacher, error)); ok {
		return rf(ctx, name, email, hashedPassword)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) entities.Teacher); ok {
		r0 = rf(ctx, name, email, hashedPassword)
	} else {
		r0 = ret.Get(0).(entities.Teacher)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, name, email, hashedPassword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTeacher provides a mock function with given fields: ctx, id
func (_m *TeacherRepository) DeleteTeacher(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeacher")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTeacher provides a mock function with given fields: ctx, id
func (_m *TeacherRepository) GetTeacher(ctx context.Context, id int) (entities.Teacher, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTeacher")
	}

	var r0 entities.Teacher
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (entities.Teacher, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) entities.Teacher); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.Teacher)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeacherByEmail provides a mock function with given fields: ctx, email
func (_m *TeacherRepository) GetTeacherByEmail(ctx context.Context, email string) (entities.Teacher, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetTeacherByEmail")
	}

	var r0 entities.Teacher
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Teacher, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Teacher); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(entities.Teacher)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTeacherRepository creates a new instance of TeacherRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeacherRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeacherRepository {
	mock := &TeacherRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
