basePath: /
definitions:
  dto.CodeSolution:
    properties:
      code:
        type: string
      lang:
        type: string
    required:
    - code
    - lang
    type: object
  dto.CourseForStudent:
    properties:
      description:
        type: string
      id:
        type: integer
      problems:
        items:
          $ref: '#/definitions/dto.ProblemForCourse'
        type: array
      title:
        type: string
    type: object
  dto.ErrorBody:
    properties:
      error:
        example: error msg
        type: string
    type: object
  dto.Login:
    properties:
      email:
        type: string
      is_student:
        type: boolean
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.OkBody:
    properties:
      detail:
        example: detail msg
        type: string
    type: object
  dto.ProblemForCourse:
    properties:
      id:
        type: integer
      title:
        type: string
    type: object
  dto.StudentRegistration:
    properties:
      class:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - class
    - email
    - name
    - password
    type: object
  dto.TeacherRegistration:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  entities.Problem:
    properties:
      course_id:
        type: integer
      description:
        type: string
      id:
        type: integer
      test_cases:
        items:
          $ref: '#/definitions/entities.TestCase'
        type: array
      title:
        type: string
    type: object
  entities.TestCase:
    properties:
      input:
        type: string
      output:
        type: string
      test_num:
        type: integer
    type: object
host: localhost:8081
info:
  contact: {}
  description: API documentation for Runlet
  title: Runlet API
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: Login endpoint
      parameters:
      - description: Data for login
        in: body
        name: loginData
        required: true
        schema:
          $ref: '#/definitions/dto.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.OkBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorBody'
        "500":
          description: Internal error
          schema:
            type: string
      summary: Login
      tags:
      - auth
  /api/auth/logout:
    post:
      consumes:
      - application/json
      description: Logout endpoint
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.OkBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorBody'
        "500":
          description: Internal error
          schema:
            type: string
      summary: Logout
      tags:
      - auth
  /api/auth/registration_student:
    post:
      consumes:
      - application/json
      description: Registration endpoint for student
      parameters:
      - description: Data for registration student
        in: body
        name: registrationData
        required: true
        schema:
          $ref: '#/definitions/dto.StudentRegistration'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.OkBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorBody'
        "500":
          description: Internal error
          schema:
            type: string
      summary: StudentRegister
      tags:
      - auth
  /api/auth/registration_teacher:
    post:
      consumes:
      - application/json
      description: Registration endpoint for teacher
      parameters:
      - description: Data for registration teacher
        in: body
        name: registrationData
        required: true
        schema:
          $ref: '#/definitions/dto.TeacherRegistration'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.OkBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorBody'
        "500":
          description: Internal error
          schema:
            type: string
      summary: TeacherRegister
      tags:
      - auth
  /api/student/courses/:
    get:
      consumes:
      - application/json
      description: Returns all student's courses
      produces:
      - application/json
      responses:
        "200":
          description: Example of course data
          schema:
            items:
              $ref: '#/definitions/dto.CourseForStudent'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorBody'
        "500":
          description: Internal error
          schema:
            type: string
      summary: GetMyCourses
      tags:
      - student/courses
  /api/student/courses/{course_id}/problems:
    get:
      consumes:
      - application/json
      description: Returns student's problems by course
      parameters:
      - description: Course ID
        in: path
        name: course_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Example of problem data
          schema:
            items:
              $ref: '#/definitions/entities.Problem'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorBody'
        "500":
          description: Internal error
          schema:
            type: string
      summary: GetMyProblems
      tags:
      - student/courses
  /api/student/problems/{problem_id}/send_solution:
    post:
      consumes:
      - application/json
      description: Sending solutions code
      parameters:
      - description: Problem ID
        in: path
        name: problem_id
        required: true
        type: integer
      - description: Data for sending code solution
        in: body
        name: sendCodeData
        required: true
        schema:
          $ref: '#/definitions/dto.CodeSolution'
      produces:
      - application/json
      responses:
        "200":
          description: Example of response
          schema:
            items:
              $ref: '#/definitions/entities.Problem'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorBody'
        "500":
          description: Internal error
          schema:
            type: string
      summary: SendSolution
      tags:
      - student/problems
swagger: "2.0"
